#ifndef PLAYER_CONFIG_H
#define PLAYER_CONFIG_H

#define   spritesheetAddress  "src/Assets/goku_placeholder.png"
#define   FRAME_WIDTH   (64.0f)
#define   FRAME_HEIGHT  (64.0f)

#define   PLAYER_WIDTH        (20.0f)
#define   PLAYER_HEIGHT       (40.0f)
#define   PLAYER_SPEED        (200.0f)

#define   PLAYER_PUSH_BOX_WIDTH     (13)
#define   PLAYER_PUSH_BOX_HEIGHT    (17)

#define   PLAYER_MOVE_MOVEMENT_AIR_MULTIPLIER  (0.75f)
#define   PLAYER_MOVEMENT_AIR_MULTIPLIER        (0.025f)
#define   PLAYER_MOVEMENT_FLOOR_MULTIPLIER      (0.025f)

#define   PLAYER_ATK1_BOX_X_OFFSET              (PLAYER_WIDTH)
#define   PLAYER_ATK1_BOX_Y_OFFSET              (PLAYER_HEIGHT/4)
#define   PLAYER_ATK1_BOX_WIDTH                 (30.0f)
#define   PLAYER_ATK1_BOX_HEIGHT                (3*PLAYER_HEIGHT/4)
#define   ATK1_DURATION                         (0.5f)

#define   PLAYER_HURT_BOX_X_OFFSET  (0)
#define   PLAYER_HURT_BOX_Y_OFFSET  (0)
#define   PLAYER_HURT_BOX_WIDTH     (PLAYER_PUSH_BOX_WIDTH)
#define   PLAYER_HURT_BOX_HEIGHT    (PLAYER_PUSH_BOX_HEIGHT)

//TODO: If sprite is centered, all X offsets follow this formula. If they all have the same Y reference, same thing.
//This might be reduced to an only one define
#define PLAYER_IDLE_SPRITE_OFFSET_X ((PLAYER_PUSH_BOX_WIDTH - FRAME_WIDTH) / 2.0f)
#define PLAYER_IDLE_SPRITE_OFFSET_Y (2*PLAYER_PUSH_BOX_HEIGHT - FRAME_HEIGHT)
#define PLAYER_MOVE_SPRITE_OFFSET_X ((PLAYER_PUSH_BOX_WIDTH - FRAME_WIDTH) / 2.0f)
#define PLAYER_MOVE_SPRITE_OFFSET_Y (2*PLAYER_PUSH_BOX_HEIGHT - FRAME_HEIGHT)
#define PLAYER_JUMP_SPRITE_OFFSET_X ((PLAYER_PUSH_BOX_WIDTH - FRAME_WIDTH) / 2.0f)
#define PLAYER_JUMP_SPRITE_OFFSET_Y (2*PLAYER_PUSH_BOX_HEIGHT - FRAME_HEIGHT)
#define PLAYER_FALL_SPRITE_OFFSET_X ((PLAYER_PUSH_BOX_WIDTH - FRAME_WIDTH) / 2.0f)
#define PLAYER_FALL_SPRITE_OFFSET_Y (2*PLAYER_PUSH_BOX_HEIGHT - FRAME_HEIGHT)
#define PLAYER_ATK1_SPRITE_OFFSET_X ((PLAYER_PUSH_BOX_WIDTH - FRAME_WIDTH) / 2.0f)
#define PLAYER_ATK1_SPRITE_OFFSET_Y (2*PLAYER_PUSH_BOX_HEIGHT - FRAME_HEIGHT)
#define PLAYER_BLOCK_SPRITE_OFFSET_X ((PLAYER_PUSH_BOX_WIDTH - FRAME_WIDTH) / 2.0f)
#define PLAYER_BLOCK_SPRITE_OFFSET_Y (2*PLAYER_PUSH_BOX_HEIGHT - FRAME_HEIGHT)
#endif